

export const plantListLibrary = [
    {
        image: require('../assets/images/plants/allium-sativum.jpg'),
        scientificName: 'Allium sativum',
        localName: 'Bawang',
        description: 'description of bawang',
        use: 'uses of bawang',
        taxonomy: '',
        category: ['medicine','food','aromatic'],
        id: '1',
    },
    {
        image: require('../assets/images/plants/blumea-balsamifera.jpg'),
        scientificName: 'Blumea balsamifera',
        localName: 'Sambong',
        description: 'In the Philippines, where it is most commonly known as sambong, Blumea balsamifera is used in traditional herbal medicine for the common cold and as a diuretic. It is also used for infected wounds, respiratory infections, and stomach pains in Thai and Chinese folk medicine. The genus Blumea is found in the tropical and sub-tropical zones of Asia, especially the Indian Subcontinent and Southeast Asia. Blumea balsamifera is one of its species that is used in Southeast Asia. A weed, this plant is a ruderal species that often grows on disturbed land, and in grasslands.',
        use: 'Its primary uses are as a diuretic (or "water pill") and to treat symptoms of the common cold. As a diuretic, sambong is an herb used to treat urolithiasis (urinary tract or kidney stones) and urinary tract infections, and thus reduces high blood pressure. Sambong works as an expectorant, an antidiarrheal and an antispasmodic, all of which treat some symptoms of the common cold. It is also sometimes used as an astringent for wounds. It is approved by the Philippine Department of Health, Institute of Traditional and Alternative Health Care, and by the Bureau of Plant Industries of the Department of Agriculture.',
        category: ['medicine','aromatic'],
        id: '2',
    },
    {
        image: require('../assets/images/plants/clinopodium-douglasii.jpg'),
        scientificName: 'Clinopodium douglasii',
        localName: 'Yerba Buena',
        description: 'description of Yerba Buena',
        use: 'uses of Yerba Buena',
        taxonomy: '',
        category: ['medicine','aromatic'],
        id: '3',
    },
    {
        image: require('../assets/images/plants/combretum-indicum.jpg'),
        scientificName: 'Combretum indicum',
        localName: 'Niyug-niyogan',
        description: 'description of Niyug-niyogan',
        use: 'uses of Niyug-niyogan',
        taxonomy: '',
        category: ['medicine','aromatic'],
        id: '4',
    },
    {
        image: require('../assets/images/plants/ehretia-microphylla.jpg'),
        scientificName: 'Ehretia microphylla',
        localName: 'Tsaang-Gubat',
        description: 'Ehretia microphylla is a shrub growing to 4 m height, with long, straggling, slender branches. It is deciduous during the dry season. Its leaves are usually 10–50 mm long and 5–30 mm wide, and may vary in size, texture, color and margin. It has small white flowers 8–10 mm in diameter with a 4–5 lobed corolla, and drupes 4–6 mm in diameter, ripening brownish orange.',
        use: 'The plant is popular in Penjing in China. The leaves are used medicinally in the Philippines to treat cough, colic, diarrhea and dysentery.',
        category: ['medicine'],
        id: '5',
    },
    {
        image: require('../assets/images/plants/momordica-charantia.jpg'),
        scientificName: 'Momordica charantia',
        localName: 'Ampalaya',
        description: 'description of Ampalaya',
        use: 'uses of Ampalaya',
        taxonomy: '',
        category: ['medicine','aromatic'],
        id: '6',
    },
    {
        image: require('../assets/images/plants/peperomia-pellucida.jpg'),
        scientificName: 'Peperomia pellucida',
        localName: 'Ulasimang Bato',
        description: 'description of Ulasimang Bato',
        use: 'uses of Ulasimang Bato',
        taxonomy: '',
        category: ['medicine','aromatic'],
        id: '7',
    },
    {
        image: require('../assets/images/plants/psidium-guajava.jpg'),
        scientificName: 'Psidium guajava',
        localName: 'Bayabas',
        description: 'Widely cultivated in tropical and subtropical regions around the world, guava fruits can range in size from as small as an apricot to as large as a grapefruit. Various cultivars have white, pink, or red flesh; a few varieties feature red (instead of green or yellow) skin. When cultivated from seed, guavas are notable for their extremely slow growth rate for several months, before a very rapid acceleration in growth rate takes over. From seed, common guavas may bloom and set fruit in as few as two years or as many as eight. Cuttings, grafting, and air layering are more commonly used as a propagation method in commercial groves. Highly adaptable, guavas can be easily grown as container plants in temperate regions, though their ability to bloom and set fruit is somewhat less predictable. In some tropical locations, guavas can become invasive. It has become a major problem in the Galápagos Islands. The plant is used in many different shampoo products for its scent. It is also becoming a popular bonsai species and is currently quite popular in India and Eastern Asia.',
        use: 'Psidium guajava has been used in traditional medicine by many cultures throughout Central America, the Caribbean, Africa, and Asia. It is used for inflammation, diabetes, hypertension, caries, wounds, pain relief, fever, diarrhea, rheumatism, lung diseases, and ulcers. Guava is an edible fruit, and can be eaten raw or cooked. The processing of the fruits yields by-products that can be fed to livestock. The leaves can also be used as fodder.',
        category: ['medicine','food'],
        id: '8',
    },
    {
        image: require('../assets/images/plants/senna-alata.jpg'),
        scientificName: 'Senna alata',
        localName: 'Akapulko',
        description: 'description of Akapulko',
        use: 'uses of Akapulko',
        taxonomy: '',
        category: ['medicine','aromatic'],
        id: '9',
    },
    {
        image: require('../assets/images/plants/vitex-negundo.jpg'),
        scientificName: 'Vitex Negundo',
        localName: 'Lagundi',
        description: 'Vitex negundo, commonly known as the Chinese chaste tree, five-leaved chaste tree, or horseshoe vitex, or nisinda is a large aromatic shrub with quadrangular, densely whitish, tomentose branchlets. It is widely used in folk medicine, particularly in South and Southeast Asia.',
        use: 'Purified extracts are believed to have medicinal properties. Vitex negundo is used for treating stored garlic against pests and as a cough remedy in the Philippines, sold under the trade names Ascof and Plemex. In Malaysia, it is used in traditional herbal medicine for womens health, including treatments for regulating the menstrual cycle, fibrocystic breast disease and postpartum remedies.',
        taxonomy: 'Plants (Kingdom Plantae)\n   ⤷Vascular Plants (Phylum Tracheophyta)\n        ⤷Flowering Plants (Subphylum Angiospermae)\n            ⤷Dicots (Class Magnoliopsida)\n                 ⤷Mints, Plantains, Olives, and Allies (Order Lamiales)\n                    ⤷Mint Family (Family Lamiaceae)\n                       ⤷Subfamily Viticoideae\n                            ⤷Genus Vitex\n                              ⤷Five-leaved Chaste Tree (Vitex negundo)\n                              ⤷Vitex negundo var. cannabifolia\n                              ⤷Vitex negundo var. heterophylla\n                              ⤷Vitex negundo var. negundo',
        category: ['medicine','aromatic'],
        id: '10',
    },
    {
        image: require('../assets/images/plants/test-plant.jpg'),
        scientificName: 'Food and Medicine Plant Sample',
        localName: 'Sample Name Food and Medicine',
        description: 'Widely cultivated in tropical and subtropical regions around the world, guava fruits can range in size from as small as an apricot to as large as a grapefruit. Various cultivars have white, pink, or red flesh; a few varieties feature red (instead of green or yellow) skin. When cultivated from seed, guavas are notable for their extremely slow growth rate for several months, before a very rapid acceleration in growth rate takes over. From seed, common guavas may bloom and set fruit in as few as two years or as many as eight. Cuttings, grafting, and air layering are more commonly used as a propagation method in commercial groves. Highly adaptable, guavas can be easily grown as container plants in temperate regions, though their ability to bloom and set fruit is somewhat less predictable. In some tropical locations, guavas can become invasive. It has become a major problem in the Galápagos Islands. The plant is used in many different shampoo products for its scent. It is also becoming a popular bonsai species and is currently quite popular in India and Eastern Asia.',
        use: 'Psidium guajava has been used in traditional medicine by many cultures throughout Central America, the Caribbean, Africa, and Asia. It is used for inflammation, diabetes, hypertension, caries, wounds, pain relief, fever, diarrhea, rheumatism, lung diseases, and ulcers. Guava is an edible fruit, and can be eaten raw or cooked. The processing of the fruits yields by-products that can be fed to livestock. The leaves can also be used as fodder.',
        category: ['medicine','food'],
        id: '11',
    },
    {
        image: require('../assets/images/plants/test-plant.jpg'),
        scientificName: 'Food Plant Sample',
        localName: 'Sample Name Food',
        description: 'Widely cultivated in tropical and subtropical regions around the world, guava fruits can range in size from as small as an apricot to as large as a grapefruit. Various cultivars have white, pink, or red flesh; a few varieties feature red (instead of green or yellow) skin. When cultivated from seed, guavas are notable for their extremely slow growth rate for several months, before a very rapid acceleration in growth rate takes over. From seed, common guavas may bloom and set fruit in as few as two years or as many as eight. Cuttings, grafting, and air layering are more commonly used as a propagation method in commercial groves. Highly adaptable, guavas can be easily grown as container plants in temperate regions, though their ability to bloom and set fruit is somewhat less predictable. In some tropical locations, guavas can become invasive. It has become a major problem in the Galápagos Islands. The plant is used in many different shampoo products for its scent. It is also becoming a popular bonsai species and is currently quite popular in India and Eastern Asia.',
        use: 'Psidium guajava has been used in traditional medicine by many cultures throughout Central America, the Caribbean, Africa, and Asia. It is used for inflammation, diabetes, hypertension, caries, wounds, pain relief, fever, diarrhea, rheumatism, lung diseases, and ulcers. Guava is an edible fruit, and can be eaten raw or cooked. The processing of the fruits yields by-products that can be fed to livestock. The leaves can also be used as fodder.',
        category: ['food'],
        id: '12',
    },
    {
        image: require('../assets/images/plants/test-plant.jpg'),
        scientificName: 'Food Plant Sample',
        localName: 'Sample Name Food',
        description: 'Widely cultivated in tropical and subtropical regions around the world, guava fruits can range in size from as small as an apricot to as large as a grapefruit. Various cultivars have white, pink, or red flesh; a few varieties feature red (instead of green or yellow) skin. When cultivated from seed, guavas are notable for their extremely slow growth rate for several months, before a very rapid acceleration in growth rate takes over. From seed, common guavas may bloom and set fruit in as few as two years or as many as eight. Cuttings, grafting, and air layering are more commonly used as a propagation method in commercial groves. Highly adaptable, guavas can be easily grown as container plants in temperate regions, though their ability to bloom and set fruit is somewhat less predictable. In some tropical locations, guavas can become invasive. It has become a major problem in the Galápagos Islands. The plant is used in many different shampoo products for its scent. It is also becoming a popular bonsai species and is currently quite popular in India and Eastern Asia.',
        use: 'Psidium guajava has been used in traditional medicine by many cultures throughout Central America, the Caribbean, Africa, and Asia. It is used for inflammation, diabetes, hypertension, caries, wounds, pain relief, fever, diarrhea, rheumatism, lung diseases, and ulcers. Guava is an edible fruit, and can be eaten raw or cooked. The processing of the fruits yields by-products that can be fed to livestock. The leaves can also be used as fodder.',
        category: ['food'],
        id: '13',
    },
    {
        image: require('../assets/images/plants/test-plant.jpg'),
        scientificName: 'Food Plant Sample',
        localName: 'Sample Name Food',
        description: 'Widely cultivated in tropical and subtropical regions around the world, guava fruits can range in size from as small as an apricot to as large as a grapefruit. Various cultivars have white, pink, or red flesh; a few varieties feature red (instead of green or yellow) skin. When cultivated from seed, guavas are notable for their extremely slow growth rate for several months, before a very rapid acceleration in growth rate takes over. From seed, common guavas may bloom and set fruit in as few as two years or as many as eight. Cuttings, grafting, and air layering are more commonly used as a propagation method in commercial groves. Highly adaptable, guavas can be easily grown as container plants in temperate regions, though their ability to bloom and set fruit is somewhat less predictable. In some tropical locations, guavas can become invasive. It has become a major problem in the Galápagos Islands. The plant is used in many different shampoo products for its scent. It is also becoming a popular bonsai species and is currently quite popular in India and Eastern Asia.',
        use: 'Psidium guajava has been used in traditional medicine by many cultures throughout Central America, the Caribbean, Africa, and Asia. It is used for inflammation, diabetes, hypertension, caries, wounds, pain relief, fever, diarrhea, rheumatism, lung diseases, and ulcers. Guava is an edible fruit, and can be eaten raw or cooked. The processing of the fruits yields by-products that can be fed to livestock. The leaves can also be used as fodder.',
        category: ['food','aromatic'],
        id: '14',
    },
    {
        image: require('../assets/images/plants/test-plant.jpg'),
        scientificName: 'Food,Medicine, and Aromatic Plant Sample',
        localName: 'Food, Medicine, and Aromatic Plant',
        description: 'Widely cultivated in tropical and subtropical regions around the world, guava fruits can range in size from as small as an apricot to as large as a grapefruit. Various cultivars have white, pink, or red flesh; a few varieties feature red (instead of green or yellow) skin. When cultivated from seed, guavas are notable for their extremely slow growth rate for several months, before a very rapid acceleration in growth rate takes over. From seed, common guavas may bloom and set fruit in as few as two years or as many as eight. Cuttings, grafting, and air layering are more commonly used as a propagation method in commercial groves. Highly adaptable, guavas can be easily grown as container plants in temperate regions, though their ability to bloom and set fruit is somewhat less predictable. In some tropical locations, guavas can become invasive. It has become a major problem in the Galápagos Islands. The plant is used in many different shampoo products for its scent. It is also becoming a popular bonsai species and is currently quite popular in India and Eastern Asia.',
        use: 'Psidium guajava has been used in traditional medicine by many cultures throughout Central America, the Caribbean, Africa, and Asia. It is used for inflammation, diabetes, hypertension, caries, wounds, pain relief, fever, diarrhea, rheumatism, lung diseases, and ulcers. Guava is an edible fruit, and can be eaten raw or cooked. The processing of the fruits yields by-products that can be fed to livestock. The leaves can also be used as fodder.',
        category: ['medicine','food','aromatic'],
        id: '15',
    }, 
    {
        image: require('../assets/images/plants/test-plant.jpg'),
        scientificName: 'Aromatic Plant Sample',
        localName: 'Sample Name Aromatic',
        description: 'Widely cultivated in tropical and subtropical regions around the world, guava fruits can range in size from as small as an apricot to as large as a grapefruit. Various cultivars have white, pink, or red flesh; a few varieties feature red (instead of green or yellow) skin. When cultivated from seed, guavas are notable for their extremely slow growth rate for several months, before a very rapid acceleration in growth rate takes over. From seed, common guavas may bloom and set fruit in as few as two years or as many as eight. Cuttings, grafting, and air layering are more commonly used as a propagation method in commercial groves. Highly adaptable, guavas can be easily grown as container plants in temperate regions, though their ability to bloom and set fruit is somewhat less predictable. In some tropical locations, guavas can become invasive. It has become a major problem in the Galápagos Islands. The plant is used in many different shampoo products for its scent. It is also becoming a popular bonsai species and is currently quite popular in India and Eastern Asia.',
        use: 'Psidium guajava has been used in traditional medicine by many cultures throughout Central America, the Caribbean, Africa, and Asia. It is used for inflammation, diabetes, hypertension, caries, wounds, pain relief, fever, diarrhea, rheumatism, lung diseases, and ulcers. Guava is an edible fruit, and can be eaten raw or cooked. The processing of the fruits yields by-products that can be fed to livestock. The leaves can also be used as fodder.',
        category: ['aromatic'],
        id: '16',
    }, 
    {
        image: require('../assets/images/plants/test-plant.jpg'),
        scientificName: 'Medicine and Aromatic Plant',
        localName: 'Sample Medicine and Aromatic',
        description: 'Widely cultivated in tropical and subtropical regions around the world, guava fruits can range in size from as small as an apricot to as large as a grapefruit. Various cultivars have white, pink, or red flesh; a few varieties feature red (instead of green or yellow) skin. When cultivated from seed, guavas are notable for their extremely slow growth rate for several months, before a very rapid acceleration in growth rate takes over. From seed, common guavas may bloom and set fruit in as few as two years or as many as eight. Cuttings, grafting, and air layering are more commonly used as a propagation method in commercial groves. Highly adaptable, guavas can be easily grown as container plants in temperate regions, though their ability to bloom and set fruit is somewhat less predictable. In some tropical locations, guavas can become invasive. It has become a major problem in the Galápagos Islands. The plant is used in many different shampoo products for its scent. It is also becoming a popular bonsai species and is currently quite popular in India and Eastern Asia.',
        use: 'Psidium guajava has been used in traditional medicine by many cultures throughout Central America, the Caribbean, Africa, and Asia. It is used for inflammation, diabetes, hypertension, caries, wounds, pain relief, fever, diarrhea, rheumatism, lung diseases, and ulcers. Guava is an edible fruit, and can be eaten raw or cooked. The processing of the fruits yields by-products that can be fed to livestock. The leaves can also be used as fodder.',
        category: ['medicine','aromatic'],
        id: '17',
    }, 
]